menu:
  หน้าแรก: /
  ภาษาอาหรับ (ระดับที่ 1):
    เกริ่นนำสู่วิชาภาษาอาหรับ: /arabic/basic/introduction-to-arabic/
#  ภาษาอาหรับ (อื่น ๆ):
#    รูปแบบคำนามที่บ่งบอกถึงความเล็ก: /arabic/reference/the-diminutive/
